### PR TITLE
base model class

### PR DESCRIPTION
**Pull request by krsnapaudel**
Abstract class

### CODE REVIEW

**Comment by krsnapaudel** [comment]
Tested using a simple model that always predicts a fixed value:
```
class AverageYieldModel(AgMLBaseModel):
  def __init__(self):
    self.average = 0.0

  def fit(self, train_dataset):
    self.average = 8.5

  def predict(self, data):
    predictions = np.full((data.shape[0], 1), self.average)
    return predictions
  
  def predict(self, test_dataset):
    predictions = np.full((len(test_dataset), 1), self.average)
    return predictions

  def save(self, model_name):
    with open(model_name, "wb") as f:
      pickle.dump(self, f)

  @classmethod
  def load(cls, model_name):
    with open(model_name, "rb") as f:
      saved_model = pickle.load(f)

    return saved_model

import os
print(os.getcwd())

average_model = AverageYieldModel()
average_model.fit(None)
average_model.save("saved_average_model.pkl")
saved_model = AverageYieldModel.load("saved_average_model.pkl")
data = np.zeros((2, 2))
print(saved_model.predict(data))
```

**Comment by krsnapaudel** [comment]
Should load be a static method or class method?

**Review by ritviksahajpal — COMMENTED** [review]
A simpler approach might be to extend scikit-learn base class as outlined here: https://scikit-learn.org/stable/developers/develop.html. The benefit of doing this is that a lot of things come for free e.g. preprocessing, cross-validation, grid-search, the ability to construct pipelines. I think this should work for folks using non scikit-learn libraries as well e.g. here is some code that extends a class from Scikit-learn and builds a PyTorch model on top of it. 

```
import torch
import torch.nn as nn
from sklearn.base import BaseEstimator, ClassifierMixin

class PyTorchClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(PyTorchClassifier, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dim),
            nn.Softmax(dim=1)
        )

    def fit(self, X, y):
        # Convert X and y to PyTorch tensors
        # Define a loss function and optimizer
        # Train the model
        pass

    def predict(self, X):
        # Convert X to a PyTorch tensor
        # Use the model to make predictions
        # Convert predictions back to a numpy array
        pass

# Usage
clf = PyTorchClassifier(input_dim=10, hidden_dim=50, output_dim=2)
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)

```

A couple of additional points:
1. Would cPickle (https://pymotw.com/2/pickle/) be better than using pickle? It is faster and that might be important when loading large ML models
2. Can you run black (https://github.com/psf/black) or ruff (https://github.com/astral-sh/ruff) for linting and formatting the code? Might be a good idea to run all code through a formatter so that even though multiple people are contributing the code looks similar.
3. Consider using dataclasses (https://towardsdatascience.com/9-reasons-why-you-should-start-using-python-dataclasses-98271adadc66) to make code more readable

**Comment by krsnapaudel** [comment]
Thanks for the suggestions @ritviksahajpal. I have formatted code with black. For the base class, I am not sure if scikit-learn base estimator is appropriate. Maybe we should have one abstract class. Then two other classes: one based on scikit-learn api and another based on torch api.

**Comment by krsnapaudel** [comment]
The main idea of the redesign comes based on input from @ronvree. The base model needs to support predict on dataset, a batch of samples and a single sample. Similarly, the api must specify what the data types of arguments and return values are.

**Pull request merged**
