### PR TITLE
benchmark overview

### PR DESCRIPTION
**Pull request by krsnapaudel**
* Benchmark overview in the README, including spatial coverage.
* Need to test if links work.
* Also consider standardizing names of directories inside `data_preparation`

### CODE REVIEW

**Review by ellaampy — CHANGES_REQUESTED** [review]
The following url references needs modification

- references/links to shapefile and crop statistics should be revised to use 2-country character code
- 
- Crop statistics fewsnet ==> https://github.com/BigDataWUR/AgML-crop-yield-forecasting/tree/main/data_preparation/crop_statistics_FEWSNET

- Shapefiles FEWSNET == > https://github.com/BigDataWUR/AgML-crop-yield-forecasting/tree/main/data_preparation/shapefiles_FEWSNET

- crop statistics for Mali does not exist (at the moment)

- ESA world cereal == > https://github.com/BigDataWUR/AgML-crop-yield-forecasting/tree/main/data_preparation/global_crop_AFIs_ESA_WC

- WorldCereal crop mask and crop calendar should be distinguished in the data sources table

- Evapotranspiration link not found in main branch

- WISE soil == > https://github.com/BigDataWUR/AgML-crop-yield-forecasting/tree/main/data_preparation/global_soil_WISE

- crop statistics DE - data preparation misspelt in link

- crop statistics US - https://github.com/BigDataWUR/AgML-crop-yield-forecasting/tree/main/data_preparation/crop_statistics_US

**Comment by krsnapaudel** [comment]
@ellaampy : Please check and let me know if the links look good now. Thanks. Note some data cards have not yet been merged.

**Review by poudelpratishtha — COMMENTED** [review]
The wheat image didn't render for me. Everything else looked good. Links work.

**Comment by krsnapaudel** [comment]
@ellaampy: Please check the most recent updates.

**Comment by ellaampy** [comment]
@krsnapaudel please modify  ...

- in the column for shapefiles, these countries are using 3-character code: Argentina, Australia and Brazil
- global_soil_wise should be **global_soil_WISE**
- global_ET0_FAO should be **global_Eto_FAO**

**Review by ellaampy — APPROVED** [review]

**Pull request merged**
