### PR TITLE
Create Readme file and Notebook to download FPAR Data

### PR DESCRIPTION
**Pull request by AbdelrahmanAmr3**
Readme file (Data Card) For AgERA5
Notebook to download FPAR Data

### CODE REVIEW

**Review by krsnapaudel — CHANGES_REQUESTED** [review]
The README is generally fine. Please add contact names (Allard and you). The data link could use the DOI.

For FPAR data preparation, the subdirectory is not required. Put the notebook in the global_fpar_500m directory.

**Comment by krsnapaudel** [comment]
Also please tag the issue number in your commits.

**Comment by AbdelrahmanAmr3** [comment]
I have made the changes

**Comment by AbdelrahmanAmr3** [comment]
> Also please tag the issue number in your commits.

Done

**Review by krsnapaudel — APPROVED** [review]
We will need to update the data card based on the new template. That we can do separately.

**Pull request merged**
