### PR TITLE
Crop calendar in a separate branch

### PR DESCRIPTION
**Pull request by poudelpratishtha**

### CODE REVIEW

**Comment by poudelpratishtha** [comment]
The script produces a rainfed crop calendar for both winter wheat and corn.

**Comment by krsnapaudel** [comment]
@poudelpratishtha : A couple of comments
1. Please remove us crop stats and shapefile related changes.
2. Let's restrict this pull request to comparison of crop calendar sources and data card for selected source.
Thanks.

**Comment by poudelpratishtha** [comment]
I removed the data preparation script from this branch. The US shapefiles were coming from an R package - tigris, so there wasn't a physical shapefile. It only has a crop calendar comparison for now. Once we have the WorldCereal dataset, we can add a data card for that.

**Comment by poudelpratishtha** [comment]
Should I put the data preparation script somewhere else then? A new directory?

**Review by poudelpratishtha — COMMENTED** [review]
Should be ready to merge.

**Review by krsnapaudel — CHANGES_REQUESTED** [review]
@poudelpratishtha : I see crop stats and shapefile changes that we have already merged. These can be removed. The `global_crop_calendar` should be in a file called `DATA-SELECTION.md` under `data_preparation`. Otherwise it looks good.

**Comment by poudelpratishtha** [comment]
I renamed the file, moved it to data_preparation, and deleted global_crop_calendar directory. Does it look good now?

**Comment by krsnapaudel** [comment]
@poudelpratishtha: I see `crop_statistics_US` and `shapefiles_US`. These must not be in this PR.

**Comment by poudelpratishtha** [comment]
I tried to undo a commit and broke git. Help?

**Comment by poudelpratishtha** [comment]
Should we try to fix it or create a new pull request?

**Comment by krsnapaudel** [comment]
@poudelpratishtha : Let's close this and create a new branch.

**Pull request closed without merging**
