### PR TITLE
added datacard for india

### PR DESCRIPTION
**Pull request by ellaampy**
describes crop statistics data on-boarded for india

### CODE REVIEW

**Review by krsnapaudel — CHANGES_REQUESTED** [review]
The data preparation needs to follow this format. [See doc here](https://docs.google.com/document/d/1FnRsrWTUayza9RaWmreomQ9aaeDxJn-pgmVeKLDxtKM/edit?usp=sharing).

**Comment by ellaampy** [comment]
@krsnapaudel thanks for your review. I didn't know about this structure and simply followed the crop_statistics_EU format. I'll adjust accordingly.

**Comment by krsnapaudel** [comment]
You are right. I also need to update the EU data preparation.

**Comment by ellaampy** [comment]
@krsnapaudel the requested changes have been submitted

**Review by krsnapaudel — APPROVED** [review]
LGTM.

**Pull request merged**
