### PR TITLE
add wise data preparation

### PR DESCRIPTION
**Pull request by ellaampy**
python notebook to prepare drainage class from wise database

### CODE REVIEW

**Review by krsnapaudel — COMMENTED** [review]
@ellaampy : Let's include the functions for AWC and pH also in the notebook.

**Comment by ellaampy** [comment]
@krsnapaudel i noticed in your original script for AWC that the operation soil_df["AWC"] = soil_df["AWC_NUM"] / soil_df["AWC_DENOM"] is repeated twice. One before ignoring root depth >=30 and another after aggregating to IDSMU. I have done similar for PH but making sure, that should be the right way.

**Comment by krsnapaudel** [comment]
Yes we are aggregating twice. First to soil type unit level, then to soil mapping unit level. You have a typo in PH code. Copy paste error from AWC code.

**Comment by ellaampy** [comment]
@krsnapaudel  on which line can I find the typo?

**Comment by krsnapaudel** [comment]
@ellaampy : Under pH section:
```
soil_df = soil_df.groupby(["IDSMU", "IDSTU", "PROP"]).agg(ROOTING_DEPTH=("BotDep", "max"),
                                                              AWC_DENOM=("DEP_DIFF", "sum"),
                                                              PHAQ_NUM=("PHAQ_NUM", "sum")).reset_index()
```

**Comment by krsnapaudel** [comment]
Soil drainage class. Update README with reference:

FAO 2006. Guidelines for soil description (Fourth ed.), FAO, Rome, 97 pftp://ftp.fao.org/agl/agll/docs/guidel_soil_descr.pdf.

**Comment by krsnapaudel** [comment]
Based on the discussion with @ajwdewit and @fcolli-JRC, add the following line:
```
soil_df = soil_df[soil_df["TAWC"] >= 0]
```

**Comment by ellaampy** [comment]
@krsnapaudel I have attempted to unify the function to prepare all variables. kindly review.

**Review by krsnapaudel — APPROVED** [review]
LGTM. We could make the log transform and pH processing more generic, but we can revisit if necessary later.

**Pull request merged**
