### PR TITLE
feature design

### PR DESCRIPTION
**Pull request by krsnapaudel**
Simple max and avg aggregation per dekad.
* Need to support other time steps
* Other type of aggregations: count and count successive.

### CODE REVIEW

**Comment by ellaampy** [comment]
@krsnapaudel can you please review the feature_design.py under my branch stella/feature-design. I tried to put it all together (for now without the count features). let me know if it is on track.

**Comment by krsnapaudel** [comment]
Feedback from @ronvree : Make feature design work with data samples:

```
# sum(indicator=”TAVG”, date_start=”0101”, date_end=”0115”)
def feature_avg(sample: dict, key="tavg", period=15, aggr_fn="mean"):
    # 2001, US-01-001, daily
    tavg_data = sample[key] # daily data
    shape_data = tavg_data.shape[0]

    # aggregate by period
    return tavg_features
```

**Comment by krsnapaudel** [comment]
Updated tests. The test for evaluation fails because evaluation code should use `predict` not `predict_batch`.

**Comment by krsnapaudel** [comment]
Based on @ronvree's feedback, moving missing feature checks to `count_threshold()`. Features can be missing for two reasons:
1. There is no data that matches filter condition (above or below threshold)
2. There is no data matching filter condition for specific period.

**Review by ronvree — APPROVED** [review]

**Pull request merged**
