### PR TITLE
Stella/data card china

### PR DESCRIPTION
**Pull request by ellaampy**
python script for on-boarding province-level crop statistics for china

### CODE REVIEW

**Review by krsnapaudel — CHANGES_REQUESTED** [review]
@ellaampy: Overall, everything looks good. The data card should now follow the [new template](https://docs.google.com/document/d/1DLuWiGuwlK__qcbmUDhcMjPtwNaTCX6zSPCcvBPuto0/edit#heading=h.ngqzjb2gk10q). Could you update to that? Thanks.

**Comment by krsnapaudel** [comment]
Also the `ipynb_checkpoints` should be in `.gitignore`.

**Comment by ellaampy** [comment]
@krsnapaudel the requested changes have been submitted.

**Review by krsnapaudel — APPROVED** [review]
@ellaampy : Your changes for China look good. But the branch has some changes for India. Could you separate them and merge those for China only? Thanks.

**Pull request merged**
